# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

r:
- 3.2
- 4.0
- oldrel
- release
- devel

r_github_packages:
  - r-lib/covr

after_success:
  - Rscript -e 'covr::codecov()'

after_faiure:
  - ./travis-tool.sh dump_logs

after_success:
  - Rscript -e 'covr::codecov()'
